# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Go Test
on:
  push:
    branches-ignore:
      - temp
defaults:
  run:
    # 指如果run的這些屬性沒有設定的時候，其預設值改為我們這裡所設定的數值
    working-directory: ./v2
jobs:
  test:
    strategy:
      matrix:
        # [ubuntu-latest, macos-latest, windows-latest]
        platform: [ windows-latest ]
        go-version: [ 1.18.x ]
    runs-on: ${{ matrix.platform }}
    name: Integration tests
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v2

      - name: go mod tidy
        run: go mod tidy

      - name: test "strings"
        run: go test ./strings

      - name: test "op"
        run: go test ./op -v

      - name: test "embed"
        run: go test ./embed -v

      # - name: test All
      #   run: go test ./...
